-- Seed data for Feature Request Board
-- Run this after creating the schema

-- Insert product channel data
INSERT INTO feature_requests (id, merchant, mrr, arr, type, category, request_group, request, context, submitted_by, date, status, asana_id, channel)
VALUES
  ('1', 'Vuori', 4200, 50400, 'integration', 'Loyalty', 'Yotpo Loyalty', 'Points balance visible in cart', 'Currently blocking upsell. Customer threatening to churn if not addressed by Q3.', 'Cole', '2026-03-08', 'pending', NULL, 'product'),
  ('2', 'Cuts Clothing', 3800, 45600, 'integration', 'Reviews', 'Bazaarvoice Reviews', 'Reviews widget in PDP', 'Enterprise merchant — part of renewal negotiation.', 'Grace', '2026-03-07', 'sent_to_slack', NULL, 'product'),
  ('3', 'Dixxon Flannel', 2900, 34800, 'integration', 'Loyalty', 'Yotpo Loyalty', 'Reward redemption at checkout', 'High-volume flash sale merchant. Same ask as Vuori.', 'Tyler', '2026-03-06', 'pending', NULL, 'product'),
  ('4', 'Jones Road Beauty', 5100, 61200, 'feature', 'Checkout', 'Apple Pay', 'Apple Pay support in web checkout flow', 'Missing parity with web. Direct impact on conversion rate.', 'Sammi', '2026-03-05', 'asana_created', 'ASN-1234', 'product'),
  ('5', 'Represent Clothing', 3400, 40800, 'feature', 'Checkout', 'Apple Pay', 'Add to cart + express checkout', 'UK-based. Heavy mobile traffic. Conversion gap vs desktop is significant.', 'Geoff', '2026-03-04', 'pending', NULL, 'product'),
  ('6', 'Good American', 6200, 74400, 'integration', 'Subscriptions', 'Recharge Subscriptions', 'Subscribe & save on PDP', 'New logo. Feature parity required before full launch.', 'Lauren', '2026-03-03', 'pending', NULL, 'product'),
  ('7', 'Alo Yoga', 7800, 93600, 'feature', 'Personalization', 'AI Recommendations', 'AI-powered product recommendations on home screen', 'Top 5 revenue merchant. Exploring AI features as part of upsell conversation.', 'Jacob', '2026-03-02', 'pending', NULL, 'product'),
  ('8', 'Madhappy', 2100, 25200, 'integration', 'Reviews', 'Bazaarvoice Reviews', 'UGC photos in PDP gallery', 'Expansion opportunity. Currently on basic plan.', 'Stacey', '2026-03-01', 'pending', NULL, 'product'),
  ('9', 'Tracksmith', 1800, 21600, 'feature', 'Checkout', 'Apple Pay', 'Works for logged-in + guest checkout', 'Running niche brand. Mobile-first audience.', 'Gina', '2026-02-28', 'pending', NULL, 'product')
ON CONFLICT (id) DO NOTHING;

-- Insert AI feedback channel data
INSERT INTO feature_requests (id, merchant, mrr, arr, type, category, request_group, request, context, submitted_by, date, status, asana_id, channel)
VALUES
  ('ai-001', 'Emi Jay', 0, 0, 'feature', 'Push Notifications', 'Push Notification Quiet Hours', 'Set ''quiet hours'' on AI pushes — Emi Jay received a lawsuit for SMS after 9pm', 'Is there a way to set ''quiet hours'' on our new AI pushes? Our customer Emi Jay received a lawsuit because they sent an SMS message past 9pm and is a little gun shy regarding our automatic pushes.', 'Gina Muir Tibbels', '2026-03-04', 'pending', NULL, 'ai'),
  ('ai-002', 'BetterGen', 0, 0, 'feature', 'Personalization', 'For You Feed', 'For You Feed beta timeline — does data pull from their specific app or cross-app?', 'For You Feed - when do we anticipate this being ready for the wider audience/not in beta? BetterGen was wondering if the data pulls from their specific app or cross-app behavior.', 'Grace Tucker', '2026-02-23', 'pending', NULL, 'ai'),
  ('ai-003', 'Unknown', 0, 0, 'integration', 'Integrations', 'Klaviyo Integration', 'Klaviyo push metrics not reflecting in Klaviyo dashboard — needs SDK fix ASAP', 'Klaviyo push metrics aren''t reflecting in the Klaviyo dashboard. Need Klaviyo SDK fix. Someone could help make these changes ASAP.', 'Geoff Burnside', '2026-03-09', 'pending', NULL, 'ai'),
  ('ai-004', 'Unknown', 0, 0, 'integration', 'Promotions', 'BOGO Integration', 'ETA on BOGO integration — nearing the finish line?', 'Hi there! ETA on BOGOs integration? We were rounding the finish line right?', 'Gina Muir Tibbels', '2026-03-06', 'pending', NULL, 'ai'),
  ('ai-005', 'Lorna Jane', 0, 0, 'feature', 'Push Notifications', 'Push Notification Consent Management', 'Pre-permission push opt-in, in-app disable, and granular consent for Lorna Jane AU', 'Large opp Lorna Jane (Australia) has hard requirements: 1) Pre-permission push notification opt-in messaging, 2) In-app way for customers to disable push notifications, 3) Granular push consent (marketing vs transactional).', 'Trevor Heiblim', '2026-02-19', 'pending', NULL, 'ai'),
  ('ai-006', 'Unknown', 0, 0, 'feature', 'Push Notifications', 'Push Opt-In Prompt', 'Push opt-in prompt settings no longer working after pop-up switch', 'Do we have the ability to edit the push opt in prompt anymore? It looks like the settings no longer work since we switched the pop up.', 'Lauren Levi', '2026-03-05', 'pending', NULL, 'ai'),
  ('ai-007', 'Unknown', 0, 0, 'feature', 'Media', 'Video Playback - Low Power Mode', 'Bypass Apple/Google low power mode to play video blocks (Instagram-style)', 'Is there a way we can bypass Apple/Google low power mode settings which prevents our video block from playing videos? Other apps like Instagram still play video on low power mode so there must be a way.', 'Sam Barati', '2026-03-06', 'pending', NULL, 'ai'),
  ('ai-008', 'Arrow Twenty Two', 0, 0, 'integration', 'Push Notifications', 'Klaviyo Integration', 'Klaviyo iOS push opens and revenue not attributed to flows and campaigns', 'Note: It looks like Android is recording opens and conversions, but iOS is not. Flows are set up via Klaviyo and pushes appear to send but revenue/opens are not tracked.', 'Jake Swartz', '2026-01-13', 'asana_created', '1212773510072980', 'ai'),
  ('ai-009', 'Princess Polly AU', 0, 0, 'feature', 'Push Notifications', 'Order Tracking Push', 'Order tracking push shows enabled but isn''t sending for Princess Polly AU', 'Princess Polly has order tracking push notifications enabled for both AU & US. The metrics are not appearing in the dashboard though sends appear to go out.', 'Stacey', '2026-01-09', 'asana_created', '1212713854952381', 'ai'),
  ('ai-010', 'GEOMETRY', 0, 0, 'feature', 'Push Notifications', 'Push Inbox Reload Bug', 'Inbox page constantly reloading when no push notifications to display', 'They haven''t sent any pushes via Tapcart recently and are seeing the notifications page in a constant reload loop.', 'Geoffrey Burnside', '2025-11-05', 'asana_created', '1211854323716371', 'ai'),
  ('ai-011', 'WoB GLB Production', 0, 0, 'feature', 'Push Notifications', 'Bloomreach Push Integration', 'Bloomreach push tokens not updating after app reinstall on Android', 'I deleted and reinstalled the app from Google Play. The login event is in Bloomreach but the push token has not updated.', 'Unknown', '2026-02-19', 'asana_created', '1213363127664662', 'ai'),
  ('ai-012', 'Pursue Fitness', 0, 0, 'feature', 'Push Notifications', 'Duplicate Inbox Messages', 'Push messages appearing multiple times in inbox on iOS (20.4.4 / 20.5.2)', 'Pursue Fitness reported seeing messages multiple times in her inbox. Confirmed on other apps running 20.4.4 and 20.5.2 — not build-specific.', 'Unknown', '2025-11-25', 'asana_created', '1212159014348224', 'ai'),
  ('ai-013', 'TOG24', 0, 0, 'feature', 'Push Notifications', 'Push Creation Custom Screen Bug', 'Push creation fails intermittently when selecting Custom Screen destination', 'Merchants intermittently see an error when creating a push notification and selecting Custom Screen as the destination. More frequent with Custom Screen specifically.', 'Unknown', '2026-02-25', 'asana_created', '1213428317286321', 'ai'),
  ('ai-014', 'Cocopup London', 0, 0, 'feature', 'Push Notifications', 'Segment Last Order Date Bug', 'Segment filter ''Last Order Date — Before'' returning incorrect user counts', 'The ''Before'' date filter on ''Purchased last 3 days'' segment returns wrong totals compared to the positive filter.', 'Unknown', '2026-02-17', 'asana_created', '1213319929970037', 'ai'),
  ('ai-015', 'buyFSA, Culture Kings NZ', 0, 0, 'feature', 'Push Notifications', 'Search Results Not Loading', '20.13.2 — Search results not loading on multiple apps pre-submission', 'Testing some apps on 20.13.2 before submitting — not seeing search results on a couple apps. Could block the 20.14 push.', 'Jesse L Tomchak', '2026-02-18', 'asana_created', '1213345561103911', 'ai'),
  ('ai-016', 'Athletic Brewing Co', 0, 0, 'feature', 'Personalization', 'AI Push Timing Controls', 'Need configurable send-time windows for AI-generated push campaigns', 'Athletic Brewing is concerned about AI pushes sending at off-hours. They need the ability to restrict AI push sends to specific time windows (e.g. 9am–8pm local time).', 'Tyler Iannantuono', '2026-03-06', 'pending', NULL, 'ai'),
  ('ai-017', 'Alo Yoga', 0, 0, 'feature', 'Personalization', 'AI Recommendations', 'AI-powered product recommendations on home screen — top merchant upsell', 'Top 5 revenue merchant exploring AI features as part of upsell conversation. Wants personalized recs on the home screen.', 'Jacob Hong', '2026-03-02', 'pending', NULL, 'ai'),
  ('ai-018', 'Unknown', 0, 0, 'feature', 'Personalization', 'AI Copy Customization', 'Ability to edit or constrain AI-generated push copy before sending', 'Multiple merchants want a ''review + edit'' step before AI pushes go out. Brand voice is critical and the current flow sends without a human approval gate.', 'Lauren Levi', '2026-03-05', 'pending', NULL, 'ai'),
  ('ai-019', 'LSKD', 0, 0, 'feature', 'Personalization', 'AI Segment Targeting', 'AI push campaigns should respect manual segment exclusions (e.g. already-purchased)', 'LSKD had AI pushes go out to customers who already purchased the product being promoted. Need suppression logic for already-converted or excluded segments.', 'Sunny Singh', '2026-02-17', 'pending', NULL, 'ai'),
  ('ai-020', 'Pebby Forevee', 0, 0, 'feature', 'Analytics', 'AI Push Performance Reporting', 'AI push performance reporting not visible in dashboard — no click/conversion data', 'Pebby Forevee reports that AI-generated pushes are not attributed separately in analytics. Hard to measure ROI vs manually created pushes.', 'Unknown', '2025-11-24', 'pending', NULL, 'ai')
ON CONFLICT (id) DO NOTHING;
