// aiFeedbackData.js
// Source: #ai-feedback Slack channel
// Schema matches requests_data.json exactly — extend this array as new messages come in,
// or replace it entirely with live data from slackSync.js

export const AI_FEEDBACK_DATA = [
  {
    id: "ai-001",
    merchant: "Emi Jay",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Push Notification Quiet Hours",
    request: "Set 'quiet hours' on AI pushes — Emi Jay received a lawsuit for SMS after 9pm",
    context: "Is there a way to set 'quiet hours' on our new AI pushes? Our customer Emi Jay received a lawsuit because they sent an SMS message past 9pm and is a little gun shy regarding our automatic pushes.",
    submittedBy: "Gina Muir Tibbels",
    date: "2026-03-04",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-002",
    merchant: "BetterGen",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Personalization",
    requestGroup: "For You Feed",
    request: "For You Feed beta timeline — does data pull from their specific app or cross-app?",
    context: "For You Feed - when do we anticipate this being ready for the wider audience/not in beta? BetterGen was wondering if the data pulls from their specific app or cross-app behavior.",
    submittedBy: "Grace Tucker",
    date: "2026-02-23",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-003",
    merchant: "Unknown",
    mrr: 0,
    arr: 0,
    type: "integration",
    category: "Integrations",
    requestGroup: "Klaviyo Integration",
    request: "Klaviyo push metrics not reflecting in Klaviyo dashboard — needs SDK fix ASAP",
    context: "Klaviyo push metrics aren't reflecting in the Klaviyo dashboard. Need Klaviyo SDK fix. Someone could help make these changes ASAP.",
    submittedBy: "Geoff Burnside",
    date: "2026-03-09",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-004",
    merchant: "Unknown",
    mrr: 0,
    arr: 0,
    type: "integration",
    category: "Promotions",
    requestGroup: "BOGO Integration",
    request: "ETA on BOGO integration — nearing the finish line?",
    context: "Hi there! ETA on BOGOs integration? We were rounding the finish line right?",
    submittedBy: "Gina Muir Tibbels",
    date: "2026-03-06",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-005",
    merchant: "Lorna Jane",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Push Notification Consent Management",
    request: "Pre-permission push opt-in, in-app disable, and granular consent for Lorna Jane AU",
    context: "Large opp Lorna Jane (Australia) has hard requirements: 1) Pre-permission push notification opt-in messaging, 2) In-app way for customers to disable push notifications, 3) Granular push consent (marketing vs transactional).",
    submittedBy: "Trevor Heiblim",
    date: "2026-02-19",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-006",
    merchant: "Unknown",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Push Opt-In Prompt",
    request: "Push opt-in prompt settings no longer working after pop-up switch",
    context: "Do we have the ability to edit the push opt in prompt anymore? It looks like the settings no longer work since we switched the pop up.",
    submittedBy: "Lauren Levi",
    date: "2026-03-05",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-007",
    merchant: "Unknown",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Media",
    requestGroup: "Video Playback - Low Power Mode",
    request: "Bypass Apple/Google low power mode to play video blocks (Instagram-style)",
    context: "Is there a way we can bypass Apple/Google low power mode settings which prevents our video block from playing videos? Other apps like Instagram still play video on low power mode so there must be a way.",
    submittedBy: "Sam Barati",
    date: "2026-03-06",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-008",
    merchant: "Arrow Twenty Two",
    mrr: 0,
    arr: 0,
    type: "integration",
    category: "Push Notifications",
    requestGroup: "Klaviyo Integration",
    request: "Klaviyo iOS push opens and revenue not attributed to flows and campaigns",
    context: "Note: It looks like Android is recording opens and conversions, but iOS is not. Flows are set up via Klaviyo and pushes appear to send but revenue/opens are not tracked.",
    submittedBy: "Jake Swartz",
    date: "2026-01-13",
    status: "in_progress",
    asanaId: "1212773510072980",
  },
  {
    id: "ai-009",
    merchant: "Princess Polly AU",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Order Tracking Push",
    request: "Order tracking push shows enabled but isn't sending for Princess Polly AU",
    context: "Princess Polly has order tracking push notifications enabled for both AU & US. The metrics are not appearing in the dashboard though sends appear to go out.",
    submittedBy: "Stacey",
    date: "2026-01-09",
    status: "in_progress",
    asanaId: "1212713854952381",
  },
  {
    id: "ai-010",
    merchant: "GEOMETRY",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Push Inbox Reload Bug",
    request: "Inbox page constantly reloading when no push notifications to display",
    context: "They haven't sent any pushes via Tapcart recently and are seeing the notifications page in a constant reload loop.",
    submittedBy: "Geoffrey Burnside",
    date: "2025-11-05",
    status: "in_progress",
    asanaId: "1211854323716371",
  },
  {
    id: "ai-011",
    merchant: "WoB GLB Production",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Bloomreach Push Integration",
    request: "Bloomreach push tokens not updating after app reinstall on Android",
    context: "I deleted and reinstalled the app from Google Play. The login event is in Bloomreach but the push token has not updated.",
    submittedBy: "Unknown",
    date: "2026-02-19",
    status: "in_progress",
    asanaId: "1213363127664662",
  },
  {
    id: "ai-012",
    merchant: "Pursue Fitness",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Duplicate Inbox Messages",
    request: "Push messages appearing multiple times in inbox on iOS (20.4.4 / 20.5.2)",
    context: "Pursue Fitness reported seeing messages multiple times in her inbox. Confirmed on other apps running 20.4.4 and 20.5.2 — not build-specific.",
    submittedBy: "Unknown",
    date: "2025-11-25",
    status: "in_progress",
    asanaId: "1212159014348224",
  },
  {
    id: "ai-013",
    merchant: "TOG24",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Push Creation Custom Screen Bug",
    request: "Push creation fails intermittently when selecting Custom Screen destination",
    context: "Merchants intermittently see an error when creating a push notification and selecting Custom Screen as the destination. More frequent with Custom Screen specifically.",
    submittedBy: "Unknown",
    date: "2026-02-25",
    status: "in_progress",
    asanaId: "1213428317286321",
  },
  {
    id: "ai-014",
    merchant: "Cocopup London",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Segment Last Order Date Bug",
    request: "Segment filter 'Last Order Date — Before' returning incorrect user counts",
    context: "The 'Before' date filter on 'Purchased last 3 days' segment returns wrong totals compared to the positive filter.",
    submittedBy: "Unknown",
    date: "2026-02-17",
    status: "in_progress",
    asanaId: "1213319929970037",
  },
  {
    id: "ai-015",
    merchant: "buyFSA, Culture Kings NZ",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Push Notifications",
    requestGroup: "Search Results Not Loading",
    request: "20.13.2 — Search results not loading on multiple apps pre-submission",
    context: "Testing some apps on 20.13.2 before submitting — not seeing search results on a couple apps. Could block the 20.14 push.",
    submittedBy: "Jesse L Tomchak",
    date: "2026-02-18",
    status: "in_progress",
    asanaId: "1213345561103911",
  },
  {
    id: "ai-016",
    merchant: "Athletic Brewing Co",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Personalization",
    requestGroup: "AI Push Timing Controls",
    request: "Need configurable send-time windows for AI-generated push campaigns",
    context: "Athletic Brewing is concerned about AI pushes sending at off-hours. They need the ability to restrict AI push sends to specific time windows (e.g. 9am–8pm local time).",
    submittedBy: "Tyler Iannantuono",
    date: "2026-03-06",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-017",
    merchant: "Alo Yoga",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Personalization",
    requestGroup: "AI Recommendations",
    request: "AI-powered product recommendations on home screen — top merchant upsell",
    context: "Top 5 revenue merchant exploring AI features as part of upsell conversation. Wants personalized recs on the home screen.",
    submittedBy: "Jacob Hong",
    date: "2026-03-02",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-018",
    merchant: "Unknown",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Personalization",
    requestGroup: "AI Copy Customization",
    request: "Ability to edit or constrain AI-generated push copy before sending",
    context: "Multiple merchants want a 'review + edit' step before AI pushes go out. Brand voice is critical and the current flow sends without a human approval gate.",
    submittedBy: "Lauren Levi",
    date: "2026-03-05",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-019",
    merchant: "LSKD",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Personalization",
    requestGroup: "AI Segment Targeting",
    request: "AI push campaigns should respect manual segment exclusions (e.g. already-purchased)",
    context: "LSKD had AI pushes go out to customers who already purchased the product being promoted. Need suppression logic for already-converted or excluded segments.",
    submittedBy: "Sunny Singh",
    date: "2026-02-17",
    status: "pending",
    asanaId: null,
  },
  {
    id: "ai-020",
    merchant: "Pebby Forevee",
    mrr: 0,
    arr: 0,
    type: "feature",
    category: "Analytics",
    requestGroup: "AI Push Performance Reporting",
    request: "AI push performance reporting not visible in dashboard — no click/conversion data",
    context: "Pebby Forevee reports that AI-generated pushes are not attributed separately in analytics. Hard to measure ROI vs manually created pushes.",
    submittedBy: "Unknown",
    date: "2025-11-24",
    status: "pending",
    asanaId: null,
  },
];
