// requestsData.js
// Source: #product Slack channel
// This data structure matches the schema expected by the Feature Request Board

export const REQUESTS_DATA = [
  {
    id: 1,
    merchant: "Vuori",
    mrr: 4200,
    arr: 50400,
    type: "integration",
    category: "Loyalty",
    requestGroup: "Yotpo Loyalty",
    request: "Points balance visible in cart",
    context: "Currently blocking upsell. Customer threatening to churn if not addressed by Q3.",
    submittedBy: "Cole",
    date: "2026-03-08",
    status: "pending",
    asanaId: null,
  },
  {
    id: 2,
    merchant: "Cuts Clothing",
    mrr: 3800,
    arr: 45600,
    type: "integration",
    category: "Reviews",
    requestGroup: "Bazaarvoice Reviews",
    request: "Reviews widget in PDP",
    context: "Enterprise merchant — part of renewal negotiation.",
    submittedBy: "Grace",
    date: "2026-03-07",
    status: "pending",
    asanaId: null,
  },
  {
    id: 3,
    merchant: "Dixxon Flannel",
    mrr: 2900,
    arr: 34800,
    type: "integration",
    category: "Loyalty",
    requestGroup: "Yotpo Loyalty",
    request: "Reward redemption at checkout",
    context: "High-volume flash sale merchant. Same ask as Vuori.",
    submittedBy: "Tyler",
    date: "2026-03-06",
    status: "pending",
    asanaId: null,
  },
  {
    id: 4,
    merchant: "Jones Road Beauty",
    mrr: 5100,
    arr: 61200,
    type: "feature",
    category: "Checkout",
    requestGroup: "Apple Pay",
    request: "Apple Pay support in web checkout flow",
    context: "Missing parity with web. Direct impact on conversion rate.",
    submittedBy: "Sammi",
    date: "2026-03-05",
    status: "in_progress",
    asanaId: "ASN-1234",
  },
  {
    id: 5,
    merchant: "Represent Clothing",
    mrr: 3400,
    arr: 40800,
    type: "feature",
    category: "Checkout",
    requestGroup: "Apple Pay",
    request: "Add to cart + express checkout",
    context: "UK-based. Heavy mobile traffic. Conversion gap vs desktop is significant.",
    submittedBy: "Geoff",
    date: "2026-03-04",
    status: "pending",
    asanaId: null,
  },
  {
    id: 6,
    merchant: "Good American",
    mrr: 6200,
    arr: 74400,
    type: "integration",
    category: "Subscriptions",
    requestGroup: "Recharge Subscriptions",
    request: "Subscribe & save on PDP",
    context: "New logo. Feature parity required before full launch.",
    submittedBy: "Lauren",
    date: "2026-03-03",
    status: "pending",
    asanaId: null,
  },
  {
    id: 7,
    merchant: "Alo Yoga",
    mrr: 7800,
    arr: 93600,
    type: "feature",
    category: "Personalization",
    requestGroup: "AI Recommendations",
    request: "AI-powered product recommendations on home screen",
    context: "Top 5 revenue merchant. Exploring AI features as part of upsell conversation.",
    submittedBy: "Jacob",
    date: "2026-03-02",
    status: "pending",
    asanaId: null,
  },
  {
    id: 8,
    merchant: "Madhappy",
    mrr: 2100,
    arr: 25200,
    type: "integration",
    category: "Reviews",
    requestGroup: "Bazaarvoice Reviews",
    request: "UGC photos in PDP gallery",
    context: "Expansion opportunity. Currently on basic plan.",
    submittedBy: "Stacey",
    date: "2026-03-01",
    status: "pending",
    asanaId: null,
  },
  {
    id: 9,
    merchant: "Tracksmith",
    mrr: 1800,
    arr: 21600,
    type: "feature",
    category: "Checkout",
    requestGroup: "Apple Pay",
    request: "Works for logged-in + guest checkout",
    context: "Running niche brand. Mobile-first audience.",
    submittedBy: "Gina",
    date: "2026-02-28",
    status: "pending",
    asanaId: null,
  },
];
